AllCops:
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Exclude:
    - "lib/slidict/llm_client.rb"
